import { UserRow } from "@/features/users-columns";

// Stand-in for `prisma.project.findMany({ select: { id: true, name: true } })`
export const MOCK_PROJECTS = [
  { id: "proj-atlas", name: "Atlas Migration" },
  { id: "proj-nebula", name: "Nebula Platform" },
  { id: "proj-helios", name: "Helios Redesign" },
  { id: "proj-orion", name: "Orion Analytics" },
  { id: "proj-vega", name: "Vega Mobile App" },
];

// Stand-in for the shaped result of:
// prisma.user.findMany({ include: { manager, assignments: { include: { project } } } })
export const MOCK_USERS: UserRow[] = [
  {
    id: "user-1",
    name: "Sarah Chen",
    email: "sarah.chen@company.com",
    role: "UNIT_MANAGER",
    seniority_level: "EXPERT",
    artifact_type: "ARCHITECTURE",
    manager: null,
    projects: [MOCK_PROJECTS[0], MOCK_PROJECTS[1]],
  },
  {
    id: "user-2",
    name: "Marcus Odom",
    email: "marcus.odom@company.com",
    role: "PEOPLE_MANAGER",
    seniority_level: "SENIOR",
    artifact_type: "CODE_REVIEW",
    manager: { id: "user-1", name: "Sarah Chen" },
    projects: [MOCK_PROJECTS[1]],
  },
  {
    id: "user-3",
    name: "Priya Nair",
    email: "priya.nair@company.com",
    role: "CONSULTANT",
    seniority_level: "MID",
    artifact_type: "HLT",
    manager: { id: "user-2", name: "Marcus Odom" },
    projects: [MOCK_PROJECTS[1], MOCK_PROJECTS[3]],
  },
  {
    id: "user-4",
    name: "Diego Ramirez",
    email: "diego.ramirez@company.com",
    role: "CONSULTANT",
    seniority_level: "JUNIOR",
    artifact_type: "LLT",
    manager: { id: "user-2", name: "Marcus Odom" },
    projects: [MOCK_PROJECTS[0]],
  },
  {
    id: "user-5",
    name: "Aisha Bello",
    email: "aisha.bello@company.com",
    role: "CONSULTANT",
    seniority_level: "SENIOR",
    artifact_type: "LLR",
    manager: { id: "user-1", name: "Sarah Chen" },
    projects: [MOCK_PROJECTS[2]],
  },
  {
    id: "user-6",
    name: "Tom Whitfield",
    email: "tom.whitfield@company.com",
    role: "PEOPLE_MANAGER",
    seniority_level: "EXPERT",
    artifact_type: "ARCHITECTURE",
    manager: null,
    projects: [MOCK_PROJECTS[2], MOCK_PROJECTS[4]],
  },
  {
    id: "user-7",
    name: "Yuki Tanaka",
    email: "yuki.tanaka@company.com",
    role: "CONSULTANT",
    seniority_level: "MID",
    artifact_type: "CODE_REVIEW",
    manager: { id: "user-6", name: "Tom Whitfield" },
    projects: [MOCK_PROJECTS[4]],
  },
  {
    id: "user-8",
    name: "Emma Larsson",
    email: "emma.larsson@company.com",
    role: "CONSULTANT",
    seniority_level: "JUNIOR",
    artifact_type: "HLT",
    manager: { id: "user-6", name: "Tom Whitfield" },
    projects: [MOCK_PROJECTS[3], MOCK_PROJECTS[4]],
  },
  {
    id: "user-9",
    name: "Karim Haddad",
    email: "karim.haddad@company.com",
    role: "CONSULTANT",
    seniority_level: "SENIOR",
    artifact_type: "LLT",
    manager: { id: "user-1", name: "Sarah Chen" },
    projects: [],
  },
  {
    id: "user-10",
    name: "Natalie Brooks",
    email: "natalie.brooks@company.com",
    role: "CONSULTANT",
    seniority_level: "MID",
    artifact_type: "LLR",
    manager: { id: "user-2", name: "Marcus Odom" },
    projects: [MOCK_PROJECTS[0], MOCK_PROJECTS[1], MOCK_PROJECTS[3]],
  },
  {
    id: "user-11",
    name: "Oliver Kim",
    email: "oliver.kim@company.com",
    role: "CONSULTANT",
    seniority_level: "EXPERT",
    artifact_type: "ARCHITECTURE",
    manager: { id: "user-6", name: "Tom Whitfield" },
    projects: [MOCK_PROJECTS[2]],
  },
  {
    id: "user-12",
    name: "Grace Mensah",
    email: "grace.mensah@company.com",
    role: "CONSULTANT",
    seniority_level: "JUNIOR",
    artifact_type: null,
    manager: { id: "user-1", name: "Sarah Chen" },
    projects: [MOCK_PROJECTS[0]],
  },
];
