import type { Metadata } from "next";
import { NuqsAdapter } from "nuqs/adapters/next/app";
import { Geist, Geist_Mono, Inter, Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import "@glideapps/glide-data-grid/dist/index.css";
import { UserProvider } from "@/context/user-context";
import { getAuthUser } from "./actions/auth";

const robotoHeading = Roboto({
  subsets: ["latin"],
  variable: "--font-heading",
});

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getAuthUser();
  const name = user?.name;
  const role = user?.role;
  return (
    <html
      lang="en"
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        "font-sans",
        inter.variable,
        robotoHeading.variable,
      )}
    >
      <body className="min-h-full flex flex-col">
        <NuqsAdapter>
          <UserProvider user={{ name, role }}>
            {children}
            <div id="portal" />
          </UserProvider>
        </NuqsAdapter>
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
